---
abstract: 'Name your accessors foo() and _set_foo()'
author:
  - 'brian greenfield, C<< <briang@cpan.org> >>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-PrivateSetters
provides:
  MooseX::PrivateSetters:
    file: lib/MooseX/PrivateSetters.pm
    version: 0.02
  MooseX::PrivateSetters::Role::Attribute:
    file: lib/MooseX/PrivateSetters/Role/Attribute.pm
    version: 0.02
requires:
  Moose: 0.94
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/briang/MooseX-PrivateSetters
version: 0.02
